{
 "title": "Project Bishop Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Среднее время выполнения команд",
   "type": "stat",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Доли COMMON и CRITICAL команд",
   "type": "piechart",
   "gridPos": { "h": 21, "w": 14, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "android_commands_common_count", "legendFormat": "COMMON" },
    {
     "expr": "android_commands_critical_count",
     "legendFormat": "CRITICAL"
    }
   ]
  },
  {
   "title": "Размер очереди",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "android_queue_size{application=\"bishop\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}